[build]
  command = ""
  publish = "static"
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "18"

# Single page app routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' wss://*.groq.com https://*.groq.com https://*.microsoft.com; media-src 'self' data: blob:;"

# API proxy for development
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.herokuapp.com/:splat"
  status = 200
  force = true

[dev]
  command = "python -m http.server 8000"
  port = 8000
  publish = "static"
  targetPort = 8000
  framework = "#custom"
